name: Shutter Indexer
networks:
- id: 100
  start_block: 34627170
  contracts:
  - name: ValidatorRegistry
    address:
    - 0xefCC23E71f6bA9B22C4D28F7588141d44496A6D6
    handler: src/EventHandlers.ts
    events:
    - event: Updated(bytes message, bytes signature)
